/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.math.BigInteger;
import java.util.ArrayList;

public class Day9 {

    public static void main(String[] args) {
        ArrayList<Integer> input = Reader.getInput();
        ArrayList<Integer> diskSpace = convertInputToDiskSpace(input);
        ArrayList<Integer> compressedDisk = compressDiskSpace(diskSpace);
//        System.out.println(compressedDisk);
//        System.out.println(calculateCheckSum(compressedDisk));
        BigInteger count = BigInteger.ZERO;
        for (int i = 0; i < compressedDisk.size(); i++) {
            count = count.add(BigInteger.valueOf(i).multiply(BigInteger.valueOf(compressedDisk.get(i))));
        }

        System.out.println(count);
//        1960677604 too low
//        1960677604 exactly the same with constructing the list only from the fileIDs
//        2147483647
//        too low means that I am moving things too far along?
//        6384282079460 correct

    }
//It was this not being a big Int :((((
    public static int calculateCheckSum(ArrayList<Integer> input) {
        int sum = 0;
        for (int index = 0; index < input.size(); index++) {
            int fileID = input.get(index);
            if(fileID == -1){
                break;
            }
            sum += (index * fileID);
        }
        return sum;
    }

    public static ArrayList<Integer> convertInputToDiskSpace(ArrayList<Integer> input) {
        ArrayList<Integer> diskSpace = new ArrayList<>();
        int fileID = 0;

        for(int index = 0; index < input.size(); index++) {
            int fileOrSpaceSize = input.get(index);
            if(index % 2 == 0){
//           file object
                for(int i = 0; i < fileOrSpaceSize; i++) {
                    diskSpace.add(fileID);
                }
                fileID++;
            } else {
//          space
                for(int i = 0; i < fileOrSpaceSize; i++) {
                    diskSpace.add(-1);
                }
            }
        }
        return diskSpace;
    }

    public static ArrayList<Integer> compressDiskSpace(ArrayList<Integer> input) {
        ArrayList<Integer> compressedDiskSpace = new ArrayList<>(input.size());
        int indexOfLastFileToMoveToFront = input.size() - 1;

        for(int index = 0; index <= input.size() -1; index++) {
            if(index > indexOfLastFileToMoveToFront) {
                break;
            }
            int fileID = input.get(index);
            if (fileID == -1) {
                indexOfLastFileToMoveToFront = findLastFileIDUpTo(input, indexOfLastFileToMoveToFront);
                if(indexOfLastFileToMoveToFront < index){
                    break;
                }
                int fileToMoveToFront = input.get(indexOfLastFileToMoveToFront);

                compressedDiskSpace.add(fileToMoveToFront);
//                    have now dealt with the lastFileID so find up to previous value
                indexOfLastFileToMoveToFront--;

            } else {
                compressedDiskSpace.add(fileID);
            }
        }

        return compressedDiskSpace;
    }


    public static int findLastFileIDUpTo(ArrayList<Integer> input, int lastFileIDIndex){
        for (int last_index = lastFileIDIndex; last_index >= 0; last_index--) {
            if(input.get(last_index) != -1)
                return last_index;
        }
        return lastFileIDIndex;
    }


}