/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;
import static org.junit.Assert.*;

public class ReaderTest {
    @Test public void appHasAGreeting() {
        Day7 classUnderTest = new Day7();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());

    }
}
