/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Day8 {
    public static void main(String[] args) {
        System.out.println("Day 8");
        Reader.getInputLinesAsString();}
}