/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.math.BigInteger;
import java.util.ArrayList;

public class Day8 {
    public static void main(String[] args) {
        System.out.println("Day 8");
    }
}